version: "3"

services:
    anser-saga-service:
        image: webdevops/php:8.0
        ports:
            - 8081:80
        working_dir: /app
        environment: 
            - WEB_DOCUMENT_ROOT=/app/public
            - PHP_MEMORY_LIMIT=512M
            - PHP_MAX_EXECUTION_TIME=30
            - PHP_POST_MAX_SIZE=20M
            - PHP_UPLOAD_MAX_FILESIZE=20M
        volumes:
            - './app:/app'
    anser-nginx:
        image: nginx
        ports:
            - "8080:80"
        volumes:
            - ./nginx/nginx.conf:/etc/nginx/nginx.conf
            - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
        environment:
            - NGINX_PORT=80
    all_DB:
        image: postgres:11.12
        environment:
            POSTGRES_DB: all
            POSTGRES_USER: root
            POSTGRES_PASSWORD: root
        ports:
            - "5432:5432"
        command: ["postgres", "-c", "logging_collector=on", "-c", "log_destination=stderr", "-c", "max_connections=10000"]